### ISSUE TITLE
Fully implement basic on-boarding flow

### ISSUE THREAD

**Issue by errrrk** [local-motion/product#21]
Depends on #5, #8, #9, #19, #20

Definition of done:
- [ ] A citizen has received an mail (#8, #9) and clicked a unique link. This link is the trigger for the web-page part of this on-boarding flow
- [ ] A citizen went through the onboarding flow (#5, #19, #20)
- [ ] After on-boarding, the citizen sees the community dashboard page (#18)
- [ ] At least one backend Axon microservice exists (probably called onboarding-service containing an `Onboarding` aggregate root)
- [ ] Onboarding related `-service`s, `-gateway`s and `-frontend`s  are deployed as docker containers on local Kube
- [ ] Business metrics on each step of the funnel (Emails sent -> emails clicked -> playground joined or created). The funnel is a 'thing' that spans multiple Epics / Functionality, so I expect a funnel-metrics-service that initially captures onboarding logic, but in the future provides a place for all funnel logic (through the fired events).
- [ ] Events are produced according to:
![Screen Shot 2018-09-25 at 16.35.09.png](https://images.zenhubusercontent.com/5ba4989cd542104d81ce65ec/a9bbce86-1d4d-45de-9120-709361a7eee5)
- [ ] - [ ] At the bottom (footer) of each screen include this text: "Rookvrije speeltuinen is een initiatief van het Longfonds en ABN AMRO" (NL) or "Smoke-free playground is an initiative of het Longfonds and ABN AMRO" (EN)
