### ISSUE TITLE
Redesign

### ISSUE THREAD

**Issue by jamalv** [local-motion/product#222]
We have been working on redesigning the front-ends to better fit the current branding of ANR and Rookvrij. This epic is meant to track progress and feedback around the redesigns.

Code and designs can be found at: https://github.com/local-motion/local-motion-redesign

**Comment by jamalv** [comment]
My main feedback right now is on the arrangement of the main workspace. I think it's confusing that there are 2 numbered parts with steps. I would suggest to merge them into one to have one overview.
![4 playground 1](https://user-images.githubusercontent.com/30194799/52705868-3d2c1b00-2f84-11e9-956c-60e11bde836d.png)

# Suggestion:
## Phase 1:
![4 playground 1](https://user-images.githubusercontent.com/30194799/52706813-8e3d0e80-2f86-11e9-92b5-565be90b4656.png)

## Phase 2:
![4 playground 2](https://user-images.githubusercontent.com/30194799/52706915-c3496100-2f86-11e9-88a3-b855c449d12d.png)

## Phase 3:
![4 playground 3](https://user-images.githubusercontent.com/30194799/52706969-e5db7a00-2f86-11e9-8c37-6274c55fb082.png)

## To consider:
I've excluded the progress indications here, but of course they should be there. One is showing how many people completed the steps, the other is showing what steps you have completed.

**Comment by maxvisser** [comment]
Whats needed to start implementing this in localmotion? As I understand this morning from @dimitriirtimid Dylan; the previous frontend developer left the team, so I think there is room to start working on implementing this redesign in the current version of localmotion onboarding-web

Maybe someone from team forus can look into dylans commits and see how he did things and pick up where he left? 
https://github.com/local-motion/onboarding-web/commits/master/src/views/Workspace/Workspace.jsx?author=dylandejonge

@dimitriirtimid what do you think?

**Comment by dimitriirtimid** [comment]
Let’s discuss this on Slack

________________________________
Van: Max Visser <notifications@github.com>
Verzonden: Thursday, February 14, 2019 4:37:39 PM
Aan: local-motion/product
CC: Dimitri Dekker; Mention
Onderwerp: Re: [local-motion/product] Redesign (#222)


Whats needed to start implementing this in localmotion? As I understand this morning from @dimitriirtimid<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdimitriirtimid&data=02%7C01%7C%7C03476c2e607f4a67743208d692925a97%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636857554609479578&sdata=38X9E03qeAahHdcrW0Fec4gbLf4INxvcf2vqT%2Fe0VH4%3D&reserved=0> Dylan; the previous frontend developer left the team, so I think there is room to start working on implementing this redesign in the current version of localmotion onboarding-web

Maybe someone from team forus can look into dylans commits and see how he did things and pick up where he left?
https://github.com/local-motion/onboarding-web/commits/master/src/views/Workspace/Workspace.jsx?author=dylandejonge<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flocal-motion%2Fonboarding-web%2Fcommits%2Fmaster%2Fsrc%2Fviews%2FWorkspace%2FWorkspace.jsx%3Fauthor%3Ddylandejonge&data=02%7C01%7C%7C03476c2e607f4a67743208d692925a97%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636857554609489589&sdata=GEvs91sudq8j7JSc6WwJybGdZOA6FA1yqtzsz%2FvmLbE%3D&reserved=0>

@dimitriirtimid<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdimitriirtimid&data=02%7C01%7C%7C03476c2e607f4a67743208d692925a97%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636857554609499600&sdata=5CAG3BedUhsKVAud%2FB31yWbpwsKQGwMwsc%2F31iP9wUs%3D&reserved=0> what do you think?

**Comment by jamalv** [comment]
@maxvisser @dimitriirtimid I am a proponent to start implementing the redesign into local-motion. 

IMO We can still work on getting more feedback on the designs though, as iterating is quicker this way. Thursday will be sprint demo, right? This seems like a good moment for that.

In the meantime; @jknnr could you work with Alex and Oxana to update the demo with the feedback from https://github.com/local-motion/product/issues/222#issuecomment-463157652 ?

**Comment by jknnr** [comment]
> In the meantime; @jknnr could you work with Alex and Oxana to update the demo with the feedback from [#222 (comment)](https://github.com/local-motion/product/issues/222#issuecomment-463157652) ?

Absolutely

**Comment by maxvisser** [comment]
@jamalv spoke with dimitri about this issue when I had a backlog session with him this morning. Our mutable conclusion was that to implement this new design completely it probably takes a big chunk of work. 

I want a design that implement all current features of localmotion in its current state, therefor I would for now try to remove some elements mainly:
- [ ] location image (beside playground name)
- [ ] user with stars 
- [ ] circles below playground title 


What I need to make a decision on implementing this design is a on each component in the design a strategy and decision:

- [ ] do we want the volunteer, petition and donation count on the bottom or top? 
- [ ] do we want cards or an action list / content area.
- [ ] what kind of picture does the play area image contain

**Comment by jamalv** [comment]
Decided during sprint demo today that we will alpha test both applications. We should define what needs to be done during this sprint to get the application ready with minimal effort.

**Comment by maxvisser** [comment]
I will close this issue for now; as we will no longer iterate on the redesign;
