### ISSUE TITLE
Epic: Content review and completion

### ISSUE THREAD

**Issue by dimitriirtimid** [local-motion/product#255]
All content in the system needs to be reviewed and completed (preferably by a communication expert). (We may do a quick scan in alpha test and a thorough review before beta test)

DoD:
- [x] welcome and explanation pages
- [x] text on cards (including 'tips' popups)
- [x] texts on all screens
- [ ] error messages (review from a config file)
- [x] email template (mailto links)
- [ ] social media templates https://github.com/local-motion/product/issues/386
- [x] Notifications https://github.com/local-motion/product/issues/373

Note that the legal/about/etc pages linked from the footer menu are already review by Yvette and others.

**Comment by maxvisser** [comment]
I will talk about this with Karin today.

**Comment by maxvisser** [comment]
I am in contact with a text writer (Annemarie) she is available, content can be ready before 21st of march maybe sooner. I will try to see which text need review or completion and contact her tomorrow.

**Comment by dimitriirtimid** [comment]
Nice!

________________________________
Van: Max Visser <notifications@github.com>
Verzonden: Wednesday, February 27, 2019 2:11:36 PM
Aan: local-motion/product
CC: Dimitri Dekker; Author
Onderwerp: Re: [local-motion/product] Content review and completion (#255)


I am in contact with a text writer (Annemarie) she is available, content can be ready before 21st of march maybe sooner. I will try to see which text need review or completion and contact her tomorrow.

**Comment by jamalv** [comment]
Related issue: https://github.com/local-motion/product/issues/274

**Comment by maxvisser** [comment]
can someone link error messages config file? @dimitriirtimid

**Comment by maxvisser** [comment]
[Concept lokaal persbericht - Rookvrij Spelen.docx](https://github.com/local-motion/product/files/3161699/Concept.lokaal.persbericht.-.Rookvrij.Spelen.docx)

**Comment by maxvisser** [comment]
[Voorbeeld enquete achterban (spelen).DEF.docx](https://github.com/local-motion/product/files/3161702/Voorbeeld.enquete.achterban.spelen.DEF.docx)

**Comment by maxvisser** [comment]
Text example website:
```
{{ playground name }} is vanaf {{ date }} rookvrij! Een rookvrije speeltuin is belangrijk om gezond en veilig te kunnen spelen. Iedereen wil dat kinderen spelen in een gezonde en veilige omgeving. Daar hoort ook een rookvrije speeltuin bij. Geen gevaar van brandwonden of kinderen die peuken oppakken en in hun mond stoppen. Daarnaast blijkt uit onderzoek dat het zien van roken kinderen aanzet om later zelf te gaan roken. Kinderen kopiëren namelijk gedrag van anderen. En hoewel gelukkig bijna geen enkel kind jonger dan 12 jaar rookt, is het wel belangrijk dat ze een gezonde sociale norm leren. Een rookvrije omgeving maakt kinderen weerbaarder om later zelf niet te gaan roken. Steeds meer speeltuinen zijn al rookvrij.

**Comment by maxvisser** [comment]
Lets make seperate issues for each content review
