### ISSUE TITLE
Design new card: Find / add playground

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#331]
## context

https://github.com/local-motion/product/issues/308

## task

![image](https://user-images.githubusercontent.com/10818702/55960826-d8ccc580-5c6d-11e9-91d6-eda812cf13f8.png)

- [x] Functionality to search playground
- [x] Show results in list
- [x] open old popup for now on button press

Old popup:
![image](https://user-images.githubusercontent.com/10818702/55960947-192c4380-5c6e-11e9-9528-9ae3b3c9b13a.png)

**Comment by KarafiziArtur** [comment]
https://github.com/local-motion/onboarding-web/pull/439
