### ISSUE TITLE
Epic: reorder workspace 

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#332]
## tasks
- [x] remove steppers
![image](https://user-images.githubusercontent.com/10818702/55151634-f61e7180-514e-11e9-980b-c14e0ee5d0af.png)

- [x] outline cards in a column (to the left)  
![image](https://user-images.githubusercontent.com/10818702/55151835-64633400-514f-11e9-837d-eb18bc724ba1.png)

- [x] add phases between cards that are part of that specific phase
     Phases: Voorbereiden, uitvoeren, onderhouden 
- [x] add a content area next to column of cards
- [x] move expanded content to new content area 

### cards content (new area)
- [x] move chat to content area
- [x] move team members to new content of team card

**Comment by maxvisser** [comment]
wireframe:
![image](https://user-images.githubusercontent.com/10818702/55169399-02b5c080-5175-11e9-87ed-141d2dbaa51f.png)

cards should contain only tile add hover effect and make them clickable to show content?
![image](https://user-images.githubusercontent.com/10818702/55169458-1bbe7180-5175-11e9-8c88-711af4adc04b.png)

https://www.draw.io/#G1-RzOukO7JdZDb1GdEXEqQnWwpXPtlwcz

**Comment by maxvisser** [comment]
Lets move all the components to the right places first and look if we need some redesign for the cards or any other ui asthetics; I like to show the picture of the card big on the content area aswell.

**Comment by maxvisser** [comment]
Just got a preview from Artur; list of cards seem pretty long as the images take alot of space in height. I think moving the images to the content area as a kind of banner is the best option to make the menu more user friendly.

**Comment by maxvisser** [comment]
If we would implement the list design these elements could be reused for this.

Non-active:
![image](https://user-images.githubusercontent.com/10818702/55393847-4d04bc00-553e-11e9-8bc5-d575615f903d.png)

Non-active done:
![image](https://user-images.githubusercontent.com/10818702/55393779-2a72a300-553e-11e9-9ac4-7763ea277870.png)

On hover/active:
![image](https://user-images.githubusercontent.com/10818702/55393665-f8614100-553d-11e9-8f98-6a5b6fd29327.png)

**Comment by KarafiziArtur** [comment]
@maxvisser Could you please check is it correctly displays?

![image](https://user-images.githubusercontent.com/6214770/55822136-99846480-5b07-11e9-901c-1ac7fa123898.png)
![image](https://user-images.githubusercontent.com/6214770/55822172-ac973480-5b07-11e9-95ad-33f63842d422.png)

**Comment by maxvisser** [comment]
You can just call gemeenschap: community :) does not need a translation.

Op di 9 apr. 2019 19:42 schreef Karafizi Arthur <notifications@github.com>:

**Comment by KarafiziArtur** [comment]
Oh, ok! I've pushed English names to PR
