### ISSUE TITLE
Alpha test

### ISSUE THREAD

**Issue by KarianneHol** [local-motion/product#41]
**Definition of done**

- [x] Write a projectplan of alfa & beta test. What is it, who do we need and when do we need them
- [x] Arrange someone to help us with finding and organising the users/testers
- [x] 10 Alfa-testers are available at the start of 2019
- [x] Alfa-tester test the alfa-version of the application
- [x] Feedback is given and usable for the next sprint

**Comment by errrrk** [comment]
"Projectplan" from my point of view is defining our most important assumptions/hypotheses. Once we have those, we can start figuring out how to test them. Hopefully the clickable wireframe that we need for the devcon is going to be useful to start validating our assumptions.

**Comment by errrrk** [comment]
We discussed: 
The '10 testers' is not the exact number we need. Most important is that we have 'some' testers and we start getting into the mode of validating our assumptions. 10 would be great, but 3 would be fine as well.

**Comment by maxvisser** [comment]
As discussed in the sprintreview session we will start doing alpha tests on the 7 of march, this sprint will be used to collect a test group and start preparing the scope and goals of the test. This will help gather user feedback and make the test an success.

@jamalv can you write up some goals for such a test, so we know what to prepare.

**Comment by maxvisser** [comment]
@KarianneHol If you are feeling better maybe we can setup a meeting to discuss this meeting before the 7th of march.

**Comment by jamalv** [comment]
## Goal
Discover which elements of both applications have the best usability; the more “free” card-style layout of the current application or the steps of the redesigned version. Do people understand what is expected of them? The first test will inspire the decisions on the strategy going forward.

## Testing scenarios: 
**Scenario 1:** User lands on “localmotion.io”
The user can land on the platform for many different reasons (link on socials, website of lungfund etc.) The assumption for this scenario is that the user has minimal knowledge about the application and does not know anybody already making a playground smoke-free.

**Scenario 2:** User gets invited to specific playground by active user.
In this scenario there is a user already active on the application on a specific playground that has performed step one; invite more people. The assumtion here is that the user is aquatinted to the person that invited them, but does not know about the platform and making playgrounds smoke-free.

## Cards version
This version supports testing both scenario’s. 

## Task-list version
This version only supports testing scenario 2.

**Comment by maxvisser** [comment]
I added #267 #268 as questions I have for an alpha test. You can comment on those seperately on how to outline this to the users.

**Comment by jamalv** [comment]
Made a project plan and briefings for the testers; please check them and share any feedback;

https://docs.google.com/document/d/1RdIwwRgLKe0z_gFt-HAileCZxe9lk5DoT1iiIqcLehk/edit?usp=sharing

**Comment by maxvisser** [comment]
I think we limit the test alot if we want to test both the lists / card application the same. I want to use Localmotion and test #267, #268 after that we can test #229;

we can send different tests to different users.

**Comment by jamalv** [comment]
How many testers do you expect to have available?

**Comment by maxvisser** [comment]
Alpha-tests are done; Testers invited to look at results in sprint demo 18 april
